'use strict';

module.exports = {
  'fade-in': {
    intent: ['enter', 'reveal'],
    use_when: ['modal open', 'toast enter', 'card appear'],
    avoid_when: ['high urgency feedback'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'fade-out': {
    intent: ['exit', 'dismiss'],
    use_when: ['dialog close', 'popover close', 'overlay fade'],
    avoid_when: ['error state emphasis'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'fade-up': {
    intent: ['enter', 'reveal'],
    use_when: ['list item appear', 'section reveal', 'card enter'],
    avoid_when: ['large distance transitions'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'fade-down': {
    intent: ['enter', 'reveal'],
    use_when: ['tooltip appear', 'dropdown enter', 'top banner reveal'],
    avoid_when: ['bottom-origin surfaces'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'fade-blur-in': {
    intent: ['reveal', 'focus'],
    use_when: ['hero reveal', 'image sharpen', 'featured card enter'],
    avoid_when: ['dense text blocks', 'tiny icons'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'fade-blur-out': {
    intent: ['exit', 'dismiss'],
    use_when: ['overlay dismiss', 'scene transition', 'content de-emphasis'],
    avoid_when: ['critical feedback', 'rapid UI close loops'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'blur-in': {
    intent: ['reveal', 'focus'],
    use_when: ['image sharpen', 'loading completion', 'depth transition'],
    avoid_when: ['plain text emphasis'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'blur-out': {
    intent: ['exit', 'de-emphasize'],
    use_when: ['background defocus', 'scene exit', 'layer transition'],
    avoid_when: ['urgent alerts'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'focus-in': {
    intent: ['focus', 'reveal'],
    use_when: ['hero reveal', 'spotlight state', 'featured content'],
    avoid_when: ['compact controls', 'busy tables'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'focus-out': {
    intent: ['exit', 'de-emphasize'],
    use_when: ['scene exit', 'focus handoff', 'hero dismiss'],
    avoid_when: ['critical state changes'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'glow-in': {
    intent: ['highlight', 'reveal'],
    use_when: ['neon highlight', 'success emphasis', 'brand accent'],
    avoid_when: ['body text', 'subtle enterprise UIs'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'slide-in-up': {
    intent: ['enter', 'nudge-attention'],
    use_when: ['toast enter', 'bottom element reveal', 'snackbar appear'],
    avoid_when: ['dense table rows'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'slide-in-left': {
    intent: ['enter', 'transition'],
    use_when: ['drawer enter', 'carousel change', 'side panel reveal'],
    avoid_when: ['centered modal open'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'slide-in-right': {
    intent: ['enter', 'transition'],
    use_when: ['toast enter', 'side panel reveal', 'next-step surface'],
    avoid_when: ['centered modal open'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'slide-in-bottom': {
    intent: ['enter', 'reveal'],
    use_when: ['bottom sheet enter', 'mobile action tray', 'sheet open'],
    avoid_when: ['top anchored surfaces'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'slide-out-down': {
    intent: ['exit', 'dismiss'],
    use_when: ['toast exit', 'snackbar dismiss', 'lightweight panel close'],
    avoid_when: ['top anchored surfaces'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'slide-out-up': {
    intent: ['exit', 'dismiss'],
    use_when: ['tooltip close', 'top banner dismiss', 'stacked list removal'],
    avoid_when: ['bottom sheets'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'slide-out-left': {
    intent: ['exit', 'transition'],
    use_when: ['drawer close', 'carousel previous', 'side panel dismiss'],
    avoid_when: ['centered modal close'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'slide-out-right': {
    intent: ['exit', 'transition'],
    use_when: ['panel close', 'wizard next handoff', 'temporary tray dismiss'],
    avoid_when: ['centered modal close'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'slide-out-bottom': {
    intent: ['exit', 'dismiss'],
    use_when: ['bottom sheet exit', 'mobile action tray close', 'sheet dismiss'],
    avoid_when: ['top anchored surfaces'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'accordion-down': {
    intent: ['expand', 'reveal'],
    use_when: ['faq open', 'accordion open', 'collapsible section expand'],
    avoid_when: ['unknown content height without css var'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'accordion-up': {
    intent: ['collapse', 'dismiss'],
    use_when: ['faq close', 'accordion close', 'collapsible section collapse'],
    avoid_when: ['unknown content height without css var'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'scale-in': {
    intent: ['enter', 'focus'],
    use_when: ['menu open', 'small popover', 'compact dialog'],
    avoid_when: ['full-screen transitions'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'scale-out': {
    intent: ['exit', 'dismiss'],
    use_when: ['menu close', 'popover dismiss', 'compact dialog exit'],
    avoid_when: ['large containers'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'zoom-in': {
    intent: ['enter', 'emphasis'],
    use_when: ['modal open', 'media focus', 'hero card enter'],
    avoid_when: ['micro interactions', 'dense list items'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'zoom-out': {
    intent: ['exit', 'dismiss'],
    use_when: ['modal close', 'focused media exit', 'hero card dismiss'],
    avoid_when: ['micro interactions'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'bounce-in': {
    intent: ['feedback', 'emphasis'],
    use_when: ['badge pop', 'reward moment', 'playful confirmation'],
    avoid_when: ['serious enterprise flows', 'critical alerts'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  wobble: {
    intent: ['feedback', 'warning'],
    use_when: ['error nudge', 'invalid input hint', 'playful warning'],
    avoid_when: ['large surfaces', 'continuous looping'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  jelly: {
    intent: ['emphasis', 'feedback'],
    use_when: ['cta click feedback', 'badge highlight', 'success micro interaction'],
    avoid_when: ['critical alerts', 'large blocks of text'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'soft-pulse': {
    intent: ['status', 'ambient'],
    use_when: ['live status', 'presence dot', 'soft attention loop'],
    avoid_when: ['urgent alerts', 'large cards'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  float: {
    intent: ['ambient', 'decorative'],
    use_when: ['ambient card', 'hero illustration', 'background accent'],
    avoid_when: ['forms', 'data-dense components'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'shake-x': {
    intent: ['error', 'feedback'],
    use_when: ['form error', 'invalid credential', 'blocked action'],
    avoid_when: ['success states', 'large layout containers'],
    reduced_motion: 'motion-reduce:animate-none',
  },
  'rotate-in': {
    intent: ['reveal', 'emphasis'],
    use_when: ['icon reveal', 'badge flourish', 'playful entry'],
    avoid_when: ['body text', 'serious workflows'],
    reduced_motion: 'motion-reduce:animate-none',
  },
};
